Update utils.js
camtheperson/get-my-ps5 pull request #24
Opened 2020-12-11 19:03 UTC by outphase84

added error hardening for failures to retrieve page

2020-12-11 22:18 UTC, camtheperson commented
@outphase84 Please update your target branch from `camtheperson:master` to `camtheperson:rc/1.2.0` (https://github.com/camtheperson/get-my-ps5/tree/rc/1.2.0).

2020-12-11 22:19 UTC, camtheperson requested changes

2020-12-11 22:19 UTC, camtheperson commented on utils.js
> +    var responseStatus;
Change to `let` instead of using `var` here.

2020-12-11 22:44 UTC, camtheperson commented on utils.js
> +    var responseStatus;
You can also chain them, like:
```
let response, responseBody, responseStatus;
```

2020-12-12 04:22 UTC, outphase84 commented
Replaced function scope decs with block scope.  Kept explicit declaration instead of chained, my OCD doesn't like chaining declarations

2020-12-12 16:42 UTC, camtheperson approved these changes

2020-12-12 16:43 UTC, merged