Use xdg-open instead of nvlc on Linux systems
camtheperson/get-my-ps5 pull request #50
Opened 2020-12-14 18:51 UTC by ReillyBrogan

`xdg-open` is more generic than `nvlc` and will open whatever is registered with the desktop environment for handling mp3 files (which could be VLC). This removes the dependency on VLC for Linux systems.

Tested on Solus Linux
Documentation indicates this should work on Debian/Ubuntu and Fedora (the package appears to be installed by default on systems that have DEs installed)

2020-12-14 18:56 UTC, jasonraimondi requested changes
👍 thanks for updating, this change slipped my mind. This is definitely a change for the better.

I would just update the https://github.com/camtheperson/get-my-ps5/blob/master/docs/usage.md#searching-for-your-playstation-5 with the new required package.

2020-12-14 18:57 UTC, camtheperson requested changes
@ReillyBrogan Please update the docs per @jasonraimondi's suggestion.

Also, please target your PR to `camtheperson:rc/1.3.0`. Thanks.

2020-12-14 20:17 UTC, ReillyBrogan commented
Both are done.

2020-12-16 02:30 UTC, camtheperson approved these changes
Nicely done. Thanks for contributing!

2020-12-16 02:30 UTC, merged